export const translations = {
    TITLE_PRESENTATION_HOME: "We transform ideas into real digital solutions.",
    RESUME_HOME: "At VC Tech, we take technology beyond ideas, developing innovative and impactful digital solutions to help you grow and succeed.",
    ABOUT_US_BUTTON: "About Us",
    OUR_SERVICES_BUTTON: "Explore Our Services",
    TITLE_ABOUT: "About Us",
    TEXT_ABOUT_PART_1: "We are an innovative team passionate about transforming digital ideas into tangible realities. With years of experience in the tech industry, we strive to provide unique solutions tailored to the needs of each client.",
    TEXT_ABOUT_PART_2: "From websites to mobile apps and cutting-edge technologies, our work revolves around creativity and practicality to ensure client success.",
    TEXT_ABOUT_PART_3: "Our goal is to create impactful solutions that foster growth and innovation, while delivering excellent user experiences and technological advances.",
    TITLE_OUR_SERVICES: "Our Services",
    SERVICE_WEB_DEVELOPMENT: "Web Development",
    SERVICE_WEB_DEVELOPMENT_DESCRIPTION: "Custom websites that combine aesthetics with functionality to ensure optimal performance and user satisfaction.",
    SERVICE_MOBILE_APPS: "Mobile Applications",
    SERVICE_MOBILE_APPS_DESCRIPTION: "Developing mobile solutions that adapt to the current needs of users, ensuring performance and usability.",
    SERVICE_ECOMMERCE: "E-commerce Solutions",
    SERVICE_ECOMMERCE_DESCRIPTION: "Helping businesses sell online with robust, scalable, and secure e-commerce platforms.",
    CONTACT_US: "Contact Us",
    FOOTER_COPYRIGHT: "© 2024 VC Tech. All rights reserved.",
    TEXT_BROWSER : "text"
};